name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
      placeholder: "When I run `python -m maestro` and type '...', it crashes with..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: "I expected Maestro to show options, but instead..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      value: |
        1. `pip install -e .`
        2. `python -m maestro`
        3. Type: "..."
        4. See error
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12.1"

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Windows 11 / macOS 14 / Ubuntu 24.04"
